### ISSUE TITLE
Supports External Files...?

### ISSUE THREAD

**Issue by ciptard** [bfintal/bfi_thumb#2]
Hi,
I've tried this script, but when i tried to crop external files (which is not in myownsite.com), the script render the original file instead of the cropped files. Is it only for internal files? Is there a way to make it works for external files?

thanks.

**Comment by iaremarkus** [comment]
I really think this topic needs to be re-opened and re-evaluated. 

I am using Amazon S3 servers to host my media and this script now doesn't work. I have plugins in place that copy all new media to an S3 instance, and then remove the local file. Perfectly acceptable way of handling media on a big site.

If this is the stance you guys are taking, then I think it should be made clear to your users that CDN's are not supported.

I don't see why allowance can't be made as @th3fallen suggested via allowing specific 'safe' URL's?
